AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EventProcessor Lambda with Lumigo tracing

Parameters:
  LumigoToken:
    Type: String
    Description: Lumigo tracer token
    Default: ''
  LumigoAnonymizeEnabled:
    Type: String
    Description: Enable anonymization
    Default: 'true'
    AllowedValues: ['true', 'false']

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        LUMIGO_TRACER_TOKEN: !Ref LumigoToken
        LUMIGO_ANONYMIZE_ENABLED: !Ref LumigoAnonymizeEnabled

Resources:
  EventProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eventProcessor
      CodeUri: ./
      Handler: eventProcessor.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          LUMIGO_TRACER_TOKEN: !Ref LumigoToken
          LUMIGO_ANONYMIZE_ENABLED: !Ref LumigoAnonymizeEnabled
      Events:
        Api:
          Type: Api
          Properties:
            Path: /process
            Method: post

Outputs:
  EventProcessorFunction:
    Description: "EventProcessor Lambda Function ARN"
    Value: !GetAtt EventProcessorFunction.Arn
  EventProcessorApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/process"
