version = 0.1
[default.deploy.parameters]
stack_name = "eventProcessor-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1756931436"
s3_prefix = "eventProcessor-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "LumigoToken=t_f8f7b905da964eef89261 LumigoAnonymizeEnabled=true"
