name: 'Pull Request'
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_types:
    name: 'Check types'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run check-types
