name: Check PR title format

on:
  pull_request:
    types:
      # Everytime a PR is opened, reopened
      - opened
      - reopened
      # Everytime a PR is edited (for example: changing the title)
      - edited
      # Everytime the PR head branch is updated (for example after pushing a new commit)
      - synchronize

jobs:
  # Job that checks the title of the PR & makes sure it fits the semantic versioning format
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disallowScopes: |
            release
